version: '3'
services:
  back:
    container_name: apollo-back
    restart: always
    build: .
    ports:
      - '8000:8000'
    volumes:
      - ./src:/usr/matthew/app/src
    links:
      - mongo
    env_file:
      - .env
  mongo:
    container_name: apollo-mongo
    image: mongo
    ports:
      - '27017:27017'
